# -*- coding: utf-8 -*-
"""RNN-text data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QihEyOTPR9Xo6P8Epq4hcVq3hr1uOpvg

RNN with sequence data
"""

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
import tensorflow.keras.models as models
import tensorflow.keras.layers as layers

# Load data
max_features = 10000
maxlen = 200

(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_features)

# Pad sequences
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)

# Build RNN for text
model = models.Sequential([
    layers.Embedding(max_features, 32, input_length=maxlen),
    layers.SimpleRNN(32),
    layers.Dense(1, activation="sigmoid")
])
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Train
history = model.fit(x_train, y_train, epochs=3, batch_size=64, validation_data=(x_test,y_test))

# Evaluate
loss, acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {acc:.4f}")