# -*- coding: utf-8 -*-
"""RNN-image data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SzMSKc04rnZslcPEUgJTKTLPLTvqUdb

RNN using tensorflow (MNIST dataset) (Image as sequence of pixels)
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import tensorflow.keras.models as models
import tensorflow.keras.layers as layers

# Load MNIST
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize
x_train = x_train / 255.0
x_test = x_test / 255.0

# Convert labels
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Input shape: (samples, time_steps, features) = (60000, 28, 28)
# Each row of 28 pixels = one timestep
model = models.Sequential([
    layers.SimpleRNN(64, input_shape=(28,28), activation="tanh"),
    layers.Dense(10, activation="softmax")
])
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

# Train
history = model.fit(x_train, y_train, epochs=5, batch_size=128, validation_data=(x_test,y_test))

# Evaluate
loss, acc = model.evaluate(x_test, y_test)
print(f"Test Accuracy: {acc:.4f}")